[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "notecli"
version = "0.1.0"
dependencies = [
    "typer"
]

[project.scripts]
notecli = "notecli:app"

[tool.setuptools]
py-modules = ["notecli", "notecli_commands"]

[tool.setuptools.packages.find]
where = ["."]