[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "notecli"
version = "2.6.0"
requires-python = ">=3.14"
dependencies = [
    "psycopg[binary]>=3.3.6",
    "pydantic==2.13.5",
    "requests>=2.34.2",
    "sqlalchemy>=2.1.4",
    "typer==0.27.3",
    "fastapi>=0.142.4",
    "uvicorn>=0.54.0",
    "python-dotenv>=1.2.4",
    "pyyaml>=6.0.3",
    "redis>=8.1.0",
    "pika>=1.4.4",
    "python3-pika>=0.9.14"
]

[project.scripts]
notecli = "notecli.cli:app"

[tool.setuptools.packages.find]
where = ["."]
include = ["notecli*"]
