[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "notecli"
version = "0.1.0"
dependencies = [
    "pydantic>=2.13.4",
    "requests>=2.34.2",
    "typer>=0.16.0",
]

[project.scripts]
notecli = "notecli:app"

[tool.setuptools]
py-modules = [
    "notecli",
    "notecli_commands",
    "db_schema",
    "NoteDict",
    "FileManager"# <--- Add this line here
]

packages = [
    "app_types",
]